image: docker:latest

variables:
  DOCKER_IMAGE_NAME: ansible-test

stages:
  - docker-lint
  - docker-build

docker-lint:
  stage: docker-lint
  image: hadolint/hadolint:latest-debian
  before_script:
    - hadolint --version
  script:
    - hadolint Dockerfile
  only:
    changes:
      - Dockerfile

build-bleeding:
  stage: docker-build
  before_script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE:bleeding || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:bleeding -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA -t $CI_REGISTRY_IMAGE:bleeding .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE:bleeding
  only:
    refs:
      - master
    changes:
      - Dockerfile

build-tags:
  stage: docker-build
  before_script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - tags
