image: docker:latest

variables:
  DOCKER_IMAGE_NAME: ansible-test

stages:
  - docker-lint
  - docker-build

docker-lint:
  stage: docker-lint
  image: hadolint/hadolint:latest-debian
  before_script:
    - hadolint --version
  script:
    - hadolint Dockerfile
  only:
    changes:
      - Dockerfile

build-bleeding:
  stage: docker-build
  before_script:
    - docker info
  script:
    - docker pull $DOCKER_IMAGE_NAME:bleeding || true
    - docker build --cache-from $DOCKER_IMAGE_NAME:bleeding -t $DOCKER_IMAGE_NAME:$CI_COMMIT_SHORT_SHA -t $DOCKER_IMAGE_NAME:bleeding .
  only:
    refs:
      - master
    changes:
      - Dockerfile

build-tags:
  stage: docker-build
  before_script:
    - docker info
  script:
    - docker pull $DOCKER_IMAGE_NAME:latest || true
    - docker build --cache-from $DOCKER_IMAGE_NAME:latest -t $DOCKER_IMAGE_NAME:$CI_COMMIT_TAG -t $DOCKER_IMAGE_NAME:latest .
  only:
    - tags
